//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen
{
    using System;
    using System.Collections.Generic;
    
    public partial class living
    {
        public int id_projivajushie { get; set; }
        public string familia { get; set; }
        public string name { get; set; }
        public string otchestvo { get; set; }
        public string sotrudnik_student { get; set; }
        public string data_zaselenia { get; set; }
        public string data_vyuezda { get; set; }
        public Nullable<int> id_komnats { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual room room { get; set; }
        public virtual User User { get; set; }
    }
}
