//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class obshagaEntities : DbContext
    {
        public obshagaEntities()
            : base("name=obshagaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<korpu> korpus { get; set; }
        public virtual DbSet<living> livings { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
